spring:
  application:
    name: gisa-user-api
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://ec2-54-157-79-121.compute-1.amazonaws.com:5432/dbarlnsbijh178}
    driverClassName: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER:pszsndrgcaeeaw}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  session:
    store-type: none
  flyway:
    baselineOnMigrate : true 
    url: ${POSTGRES_URL:jdbc:postgresql://ec2-54-157-79-121.compute-1.amazonaws.com:5432/dbarlnsbijh178}
    schemas: gisauserapidb
    password: ${POSTGRES_PASSWORD}
    user: ${POSTGRES_USER:pszsndrgcaeeaw}
    locations: classpath:db/migration
  main:
    allow-bean-definition-overriding: true
    allow-bean-definition-overriding: true
server:
  port: 
    ${PORT:8000}
    
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:https://gisa-eureka-server.herokuapp.com/eureka}   
  instance:
    preferIpAddress: true
