server:
  port: ${PORT:8000}
spring:
  application:
    name: gisa-user-api
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  session:
    store-type: none
  flyway:
    baselineOnMigrate: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}