CREATE SCHEMA IF NOT EXISTS gisauserapidb AUTHORIZATION pszsndrgcaeeaw;

DROP EXTENSION  IF EXISTS "uuid-ossp" ;
CREATE EXTENSION "uuid-ossp";

CREATE SEQUENCE IF NOT EXISTS public.seq_number
    INCREMENT 1
    START 1
    CACHE 1;
