INSERT INTO gisauserapidb.profissao (id_profissao, nome) 
VALUES	
	(gen_random_uuid(), 'Angiologista Acompanhante'),
	(gen_random_uuid(), 'Açougueiro'),
	(gen_random_uuid(), 'Acupunturista'),
	(gen_random_uuid(), 'Adestrador de animais'),
	(gen_random_uuid(), 'Administrador'),
	(gen_random_uuid(), 'Advogado'),
	(gen_random_uuid(), 'Aeromoça'),
	(gen_random_uuid(), 'Aeronauta'),
	(gen_random_uuid(), 'Afiador de ferramentas'),
	(gen_random_uuid(), 'Agente de viagens'),
	(gen_random_uuid(), 'Agente funerário'),
	(gen_random_uuid(), 'Agricultor'),
	(gen_random_uuid(), 'Agrimensor'),
	(gen_random_uuid(), 'Agrônomo'),
	(gen_random_uuid(), 'Alergologista'),
	(gen_random_uuid(), 'Alfaiate'),
	(gen_random_uuid(), 'Almirante'),
	(gen_random_uuid(), 'Almoxarife'),
	(gen_random_uuid(), 'Alpinista'),
	(gen_random_uuid(), 'Ama'),
	(gen_random_uuid(), 'Ambientalista'),
	(gen_random_uuid(), 'Ambulante'),
	(gen_random_uuid(), 'Amolador de ferramentas'),
	(gen_random_uuid(), 'Analista de sistemas'),
	(gen_random_uuid(), 'Anestesiologista'),
	(gen_random_uuid(), 'Angiologista'),
	(gen_random_uuid(), 'Antropólogologo'),
	(gen_random_uuid(), 'Apicultor'),
	(gen_random_uuid(), 'Apontador de mão de obra'),
	(gen_random_uuid(), 'Apresentador'),
	(gen_random_uuid(), 'Árbitro e mediador'),
	(gen_random_uuid(), 'Argumentista'),
	(gen_random_uuid(), 'Armador'),
	(gen_random_uuid(), 'Armeiro'),
	(gen_random_uuid(), 'Arqueólogo'),
	(gen_random_uuid(), 'Arquiteto'),
	(gen_random_uuid(), 'Arquivista'),
	(gen_random_uuid(), 'Arrumadeira'),
	(gen_random_uuid(), 'Artesão'),
	(gen_random_uuid(), 'Artista de circo'),
	(gen_random_uuid(), 'Artista plástico'),
	(gen_random_uuid(), 'Artista/Técnico em espetáculos de diversões'),
	(gen_random_uuid(), 'Ascensorista'),
	(gen_random_uuid(), 'Assessor de Imprensa'),
	(gen_random_uuid(), 'Assessor parlamentar'),
	(gen_random_uuid(), 'Assistente de cámera'),
	(gen_random_uuid(), 'Assistente de direção'),
	(gen_random_uuid(), 'Assistente de produção'),
	(gen_random_uuid(), 'Assistente social'),
	(gen_random_uuid(), 'Astrofísico'),
	(gen_random_uuid(), 'Astrologo'),
	(gen_random_uuid(), 'Astronauta'),
	(gen_random_uuid(), 'Astronomo'),
	(gen_random_uuid(), 'Atendente'),
	(gen_random_uuid(), 'Atleta de arremesso de peso'),
	(gen_random_uuid(), 'Atleta de canoagem'),
	(gen_random_uuid(), 'Atleta de nado sincronizado'),
	(gen_random_uuid(), 'Atleta de tiro com arco'),
	(gen_random_uuid(), 'Ator / Atriz'),
	(gen_random_uuid(), 'Auditor'),
	(gen_random_uuid(), 'Avalista'),
	(gen_random_uuid(), 'Aviador'),
	(gen_random_uuid(), 'Babá'),
	(gen_random_uuid(), 'Babysitter'),
	(gen_random_uuid(), 'Bailarina'),
	(gen_random_uuid(), 'Baixista'),
	(gen_random_uuid(), 'Balconista'),
	(gen_random_uuid(), 'Bancário'),
	(gen_random_uuid(), 'Barbeiro'),
	(gen_random_uuid(), 'Barman'),
	(gen_random_uuid(), 'Bartender'),
	(gen_random_uuid(), 'Baterista'),
	(gen_random_uuid(), 'Bedel'),
	(gen_random_uuid(), 'Bibliotecário'),
	(gen_random_uuid(), 'Biólogo'),
	(gen_random_uuid(), 'Biomédico'),
	(gen_random_uuid(), 'Bioquímico'),
	(gen_random_uuid(), 'Biotecnólogo'),
	(gen_random_uuid(), 'Bóia-fria'),
	(gen_random_uuid(), 'Bombeiro'),
	(gen_random_uuid(), 'Borracheiro'),
	(gen_random_uuid(), 'Boticário'),
	(gen_random_uuid(), 'Boxeador'),
	(gen_random_uuid(), 'Brigadeiro'),
	(gen_random_uuid(), 'Broker'),
	(gen_random_uuid(), 'Cabeleireiro'),
	(gen_random_uuid(), 'Cabo'),
	(gen_random_uuid(), 'Caça talentos/Olheiro'),
	(gen_random_uuid(), 'Cadeirinha'),
	(gen_random_uuid(), 'Cadista'),
	(gen_random_uuid(), 'Caixa'),
	(gen_random_uuid(), 'Caldeireiro'),
	(gen_random_uuid(), 'Cambista'),
	(gen_random_uuid(), 'CamelôÂ´'),
	(gen_random_uuid(), 'Cameraman'),
	(gen_random_uuid(), 'Caminhoneiro'),
	(gen_random_uuid(), 'Cantor'),
	(gen_random_uuid(), 'Capitão'),
	(gen_random_uuid(), 'Capoeirista Profissional'),
	(gen_random_uuid(), 'Cardiologista'),
	(gen_random_uuid(), 'Carnavalesco'),
	(gen_random_uuid(), 'Carpinteiro'),
	(gen_random_uuid(), 'Cartazeiro'),
	(gen_random_uuid(), 'Carteiro'),
	(gen_random_uuid(), 'Cartógrafo'),
	(gen_random_uuid(), 'Cartunista'),
	(gen_random_uuid(), 'Catador de material reciclável'),
	(gen_random_uuid(), 'Cenógrafo'),
	(gen_random_uuid(), 'Cenotécnico'),
	(gen_random_uuid(), 'Ceramista'),
	(gen_random_uuid(), 'Cerimonialista'),
	(gen_random_uuid(), 'Chapeiro'),
	(gen_random_uuid(), 'Chargista'),
	(gen_random_uuid(), 'Chaveiro'),
	(gen_random_uuid(), 'Chefe de Cozinha'),
	(gen_random_uuid(), 'Ciclista'),
	(gen_random_uuid(), 'Cientista'),
	(gen_random_uuid(), 'Cientista político'),
	(gen_random_uuid(), 'Cientista social'),
	(gen_random_uuid(), 'Cineasta'),
	(gen_random_uuid(), 'Cinegrafista'),
	(gen_random_uuid(), 'Cinematografo'),
	(gen_random_uuid(), 'Cirurgião bucal'),
	(gen_random_uuid(), 'Cirurgião dentista'),
	(gen_random_uuid(), 'Clap loader'),
	(gen_random_uuid(), 'Clarinetista'),
	(gen_random_uuid(), 'Classificador contábil'),
	(gen_random_uuid(), 'Clínico geral'),
	(gen_random_uuid(), 'Co-piloto'),
	(gen_random_uuid(), 'Coach'),
	(gen_random_uuid(), 'Cobaia MÃƒÂ©dica'),
	(gen_random_uuid(), 'Cobrador de ÃƒÂ´nibus'),
	(gen_random_uuid(), 'Cobrador de pedágio'),
	(gen_random_uuid(), 'Colo proctologista'),
	(gen_random_uuid(), 'Comandante'),
	(gen_random_uuid(), 'Comissário de bordo'),
	(gen_random_uuid(), 'Compositor'),
	(gen_random_uuid(), 'Comprador'),
	(gen_random_uuid(), 'Confeiteiro'),
	(gen_random_uuid(), 'Cozinheiro'),
	(gen_random_uuid(), 'Dançarina'),
	(gen_random_uuid(), 'Datilógrafo'),
	(gen_random_uuid(), 'Decorador'),
	(gen_random_uuid(), 'Dedetizador'),
	(gen_random_uuid(), 'Defensor Público'),
	(gen_random_uuid(), 'Degustador'),
	(gen_random_uuid(), 'Delegado'),
	(gen_random_uuid(), 'Dentista'),
	(gen_random_uuid(), 'Deputado'),
	(gen_random_uuid(), 'Dermatologista'),
	(gen_random_uuid(), 'Desembargador de justiça'),
	(gen_random_uuid(), 'Desenhista'),
	(gen_random_uuid(), 'Desenhista Industrial'),
	(gen_random_uuid(), 'Designer de Interiores'),
	(gen_random_uuid(), 'Designer de moda'),
	(gen_random_uuid(), 'Designer de produto'),
	(gen_random_uuid(), 'Designer gráfico'),
	(gen_random_uuid(), 'Despachante'),
	(gen_random_uuid(), 'Diagramador'),
	(gen_random_uuid(), 'Dialoguista'),
	(gen_random_uuid(), 'Diarista'),
	(gen_random_uuid(), 'Digitador'),
	(gen_random_uuid(), 'Diplomata'),
	(gen_random_uuid(), 'Diretor de cinema'),
	(gen_random_uuid(), 'Diretor de fotografia'),
	(gen_random_uuid(), 'Diretor de produção'),
	(gen_random_uuid(), 'DJ'),
	(gen_random_uuid(), 'Dogueiro'),
	(gen_random_uuid(), 'Domador'),
	(gen_random_uuid(), 'Dublador'),
	(gen_random_uuid(), 'Dublê'),
	(gen_random_uuid(), 'Ecólogo'),
	(gen_random_uuid(), 'Economista'),
	(gen_random_uuid(), 'Economista doméstico'),
	(gen_random_uuid(), 'Editor'),
	(gen_random_uuid(), 'Eletricista'),
	(gen_random_uuid(), 'Embaixador'),
	(gen_random_uuid(), 'Embalador'),
	(gen_random_uuid(), 'Embalsamador'),
	(gen_random_uuid(), 'Empacotador'),
	(gen_random_uuid(), 'Empr. doméstico'),
	(gen_random_uuid(), 'Empresário'),
	(gen_random_uuid(), 'Encanador'),
	(gen_random_uuid(), 'Endocrinologista'),
	(gen_random_uuid(), 'Endodontista'),
	(gen_random_uuid(), 'Enfermeiro'),
	(gen_random_uuid(), 'Engenheiro'),
	(gen_random_uuid(), 'Engenheiro aeronáutico'),
	(gen_random_uuid(), 'Engenheiro agrícola'),
	(gen_random_uuid(), 'Engenheiro agrônomo'),
	(gen_random_uuid(), 'Engenheiro ambiental'),
	(gen_random_uuid(), 'Engenheiro bioquímico'),
	(gen_random_uuid(), 'Engenheiro civil'),
	(gen_random_uuid(), 'Engenheiro de alimentos'),
	(gen_random_uuid(), 'Engenheiro de computação'),
	(gen_random_uuid(), 'Engenheiro de materiais'),
	(gen_random_uuid(), 'Engenheiro de minas'),
	(gen_random_uuid(), 'Engenheiro de nanotecnologia'),
	(gen_random_uuid(), 'Engenheiro de processos'),
	(gen_random_uuid(), 'Engenheiro de produção'),
	(gen_random_uuid(), 'Engenheiro de produção agroindustrial'),
	(gen_random_uuid(), 'Engenheiro de produto'),
	(gen_random_uuid(), 'Engenheiro de projetos'),
	(gen_random_uuid(), 'Engenheiro de segurança do trabalho'),
	(gen_random_uuid(), 'Engenheiro de telecomunicações'),
	(gen_random_uuid(), 'Engenheiro de transportes'),
	(gen_random_uuid(), 'Engenheiro eletricista'),
	(gen_random_uuid(), 'Engenheiro físico'),
	(gen_random_uuid(), 'Engenheiro florestal'),
	(gen_random_uuid(), 'Engenheiro industrial'),
	(gen_random_uuid(), 'Engenheiro mecánico'),
	(gen_random_uuid(), 'Engenheiro mecatrônico'),
	(gen_random_uuid(), 'Engenheiro metalúrgico'),
	(gen_random_uuid(), 'Engenheiro naval'),
	(gen_random_uuid(), 'Engenheiro químico'),
	(gen_random_uuid(), 'Engenheiro sanitarista'),
	(gen_random_uuid(), 'Engenheiro têxtil'),
	(gen_random_uuid(), 'Engraxate'),
	(gen_random_uuid(), 'Enólogo'),
	(gen_random_uuid(), 'Entalhador'),
	(gen_random_uuid(), 'Epidemiólogo'),
	(gen_random_uuid(), 'Escoteiro'),
	(gen_random_uuid(), 'Escritor'),
	(gen_random_uuid(), 'Escriturário'),
	(gen_random_uuid(), 'Escrivão'),
	(gen_random_uuid(), 'Escultor'),
	(gen_random_uuid(), 'Esgrimista'),
	(gen_random_uuid(), 'Especialista em agronegócios'),
	(gen_random_uuid(), 'Espeleologista'),
	(gen_random_uuid(), 'Estampador de tecidos'),
	(gen_random_uuid(), 'Estatístico'),
	(gen_random_uuid(), 'Esteticista'),
	(gen_random_uuid(), 'Estilista'),
	(gen_random_uuid(), 'Estofador'),
	(gen_random_uuid(), 'Estoquista'),
	(gen_random_uuid(), 'Farmacêutico'),
	(gen_random_uuid(), 'Faturista'),
	(gen_random_uuid(), 'Faxineiro'),
	(gen_random_uuid(), 'Feirante'),
	(gen_random_uuid(), 'Ferramenteiro'),
	(gen_random_uuid(), 'Ferreiro'),
	(gen_random_uuid(), 'Ferroviário'),
	(gen_random_uuid(), 'Figurante'),
	(gen_random_uuid(), 'Figurinista'),
	(gen_random_uuid(), 'Filósofo'),
	(gen_random_uuid(), 'Fiscal'),
	(gen_random_uuid(), 'Físico'),
	(gen_random_uuid(), 'Físico Nuclear'),
	(gen_random_uuid(), 'Fisiculturista'),
	(gen_random_uuid(), 'Fisioterapeuta'),
	(gen_random_uuid(), 'Flautista'),
	(gen_random_uuid(), 'Florista'),
	(gen_random_uuid(), 'Fonoaudiólogo'),
	(gen_random_uuid(), 'Forneiro'),
	(gen_random_uuid(), 'Fotógrafo'),
	(gen_random_uuid(), 'Frentista'),
	(gen_random_uuid(), 'Fresador'),
	(gen_random_uuid(), 'Fundidor'),
	(gen_random_uuid(), 'Funileiro'),
	(gen_random_uuid(), 'Gagsman'),
	(gen_random_uuid(), 'Gandula'),
	(gen_random_uuid(), 'Garçom / Garçonete'),
	(gen_random_uuid(), 'Gari'),
	(gen_random_uuid(), 'Garimpeiro'),
	(gen_random_uuid(), 'Gastroenterologista'),
	(gen_random_uuid(), 'General'),
	(gen_random_uuid(), 'Geofísico'),
	(gen_random_uuid(), 'Geógrafo'),
	(gen_random_uuid(), 'Geólogo'),
	(gen_random_uuid(), 'Geradorista'),
	(gen_random_uuid(), 'Gerente de banco'),
	(gen_random_uuid(), 'Gerente de vendas'),
	(gen_random_uuid(), 'Geriatra'),
	(gen_random_uuid(), 'Gestor ambiental'),
	(gen_random_uuid(), 'Gestor publico'),
	(gen_random_uuid(), 'Ginasta artística'),
	(gen_random_uuid(), 'Ginasta rítmica'),
	(gen_random_uuid(), 'Ginecologista'),
	(gen_random_uuid(), 'Gourmet'),
	(gen_random_uuid(), 'Governador'),
	(gen_random_uuid(), 'Governanta'),
	(gen_random_uuid(), 'Grafologista'),
	(gen_random_uuid(), 'Gravurista'),
	(gen_random_uuid(), 'Guarda ou policial rodoviário'),
	(gen_random_uuid(), 'Guarda roupeiro'),
	(gen_random_uuid(), 'Guardador e lavador de veículos'),
	(gen_random_uuid(), 'Guia turístico'),
	(gen_random_uuid(), 'Guincheiro'),
	(gen_random_uuid(), 'Guitarrista'),
	(gen_random_uuid(), 'Impressor'),
	(gen_random_uuid(), 'Imunologista'),
	(gen_random_uuid(), 'Infectologista'),
	(gen_random_uuid(), 'Inspetor'),
	(gen_random_uuid(), 'Instalador de linha telefônica'),
	(gen_random_uuid(), 'Instalador de painéis'),
	(gen_random_uuid(), 'Instrumentador cirúrgico'),
	(gen_random_uuid(), 'Instrumentista musical'),
	(gen_random_uuid(), 'Instrutor'),
	(gen_random_uuid(), 'Intérprete e tradutor de língua de sinais'),
	(gen_random_uuid(), 'Investigador de Polícia'),
	(gen_random_uuid(), 'Investigador particular'),
	(gen_random_uuid(), 'Jangadeiro'),
	(gen_random_uuid(), 'Jardineiro'),
	(gen_random_uuid(), 'Jogador de basquete'),
	(gen_random_uuid(), 'Jogador de bocha'),
	(gen_random_uuid(), 'Jogador de boliche'),
	(gen_random_uuid(), 'Jogador de futebol'),
	(gen_random_uuid(), 'Jogador de golfe'),
	(gen_random_uuid(), 'Jogador de handebol'),
	(gen_random_uuid(), 'Jogador de hóquei'),
	(gen_random_uuid(), 'Jogador de tênis de mesa'),
	(gen_random_uuid(), 'Jogador de vôlei'),
	(gen_random_uuid(), 'Jóquei'),
	(gen_random_uuid(), 'Jornaleiro'),
	(gen_random_uuid(), 'Jornalista'),
	(gen_random_uuid(), 'Judoca Profissional'),
	(gen_random_uuid(), 'Juiz de direito'),
	(gen_random_uuid(), 'Juiz de futebol'),
	(gen_random_uuid(), 'Juiz ou Árbitro de futebol'),
	(gen_random_uuid(), 'Laboratorista'),
	(gen_random_uuid(), 'Lactarista Hospitalar'),
	(gen_random_uuid(), 'Lamboteiro'),
	(gen_random_uuid(), 'Lancheiro'),
	(gen_random_uuid(), 'Lanterneiro'),
	(gen_random_uuid(), 'Lapidário'),
	(gen_random_uuid(), 'Lavador'),
	(gen_random_uuid(), 'Leão de chácara'),
	(gen_random_uuid(), 'Leiloeiro'),
	(gen_random_uuid(), 'Leiteiro'),
	(gen_random_uuid(), 'Lenhador'),
	(gen_random_uuid(), 'Letrista'),
	(gen_random_uuid(), 'Levantador de peso'),
	(gen_random_uuid(), 'Líder comunitário'),
	(gen_random_uuid(), 'Limpador de vidros'),
	(gen_random_uuid(), 'Lixeiro/Coletor de Lixo'),
	(gen_random_uuid(), 'Locutor'),
	(gen_random_uuid(), 'Lubrificador de máquinas'),
	(gen_random_uuid(), 'Lutador de jiu-jitsu'),
	(gen_random_uuid(), 'Lutador de karatê'),
	(gen_random_uuid(), 'Lutador de kung fu'),
	(gen_random_uuid(), 'Lutador de luta livre'),
	(gen_random_uuid(), 'Lutador de Taekwondo'),
	(gen_random_uuid(), 'Luthier'),
	(gen_random_uuid(), 'Maestro'),
	(gen_random_uuid(), 'Mágico'),
	(gen_random_uuid(), 'Maitre'),
	(gen_random_uuid(), 'Major'),
	(gen_random_uuid(), 'Manicure'),
	(gen_random_uuid(), 'Manobrista'),
	(gen_random_uuid(), 'Maquiador'),
	(gen_random_uuid(), 'Maquinista'),
	(gen_random_uuid(), 'Marcador de luz'),
	(gen_random_uuid(), 'Marceneiro'),
	(gen_random_uuid(), 'Marechal'),
	(gen_random_uuid(), 'Marinheiro'),
	(gen_random_uuid(), 'Marketeiro'),
	(gen_random_uuid(), 'Massagista'),
	(gen_random_uuid(), 'Matemático'),
	(gen_random_uuid(), 'Mecánico'),
	(gen_random_uuid(), 'Mecánico de Vão'),
	(gen_random_uuid(), 'Mecanógrafo'),
	(gen_random_uuid(), 'Médico'),
	(gen_random_uuid(), 'Médico cirurgião'),
	(gen_random_uuid(), 'Médico de Família'),
	(gen_random_uuid(), 'Médico geneticista'),
	(gen_random_uuid(), 'Médico legista'),
	(gen_random_uuid(), 'Médico nuclear'),
	(gen_random_uuid(), 'Meeiro'),
	(gen_random_uuid(), 'Mensageiro'),
	(gen_random_uuid(), 'Mergulhador'),
	(gen_random_uuid(), 'Mestre cervejeiro'),
	(gen_random_uuid(), 'Mestre de armas'),
	(gen_random_uuid(), 'Mestre-de-obras'),
	(gen_random_uuid(), 'Metalúrgico'),
	(gen_random_uuid(), 'Meteorologista'),
	(gen_random_uuid(), 'Microfonista'),
	(gen_random_uuid(), 'Militar'),
	(gen_random_uuid(), 'Ministro'),
	(gen_random_uuid(), 'Modelista'),
	(gen_random_uuid(), 'Modelo'),
	(gen_random_uuid(), 'Moldador'),
	(gen_random_uuid(), 'Moldureiro'),
	(gen_random_uuid(), 'Moleiro'),
	(gen_random_uuid(), 'Montador'),
	(gen_random_uuid(), 'Montador de negativos'),
	(gen_random_uuid(), 'Motofrete'),
	(gen_random_uuid(), 'Motorista'),
	(gen_random_uuid(), 'Mototaxista'),
	(gen_random_uuid(), 'Museólogo'),
	(gen_random_uuid(), 'Músico'),
	(gen_random_uuid(), 'Musicoterapeuta'),
	(gen_random_uuid(), 'Nadador'),
	(gen_random_uuid(), 'Naturólogo'),
	(gen_random_uuid(), 'Navegador'),
	(gen_random_uuid(), 'Nefrologista'),
	(gen_random_uuid(), 'Neonatologista'),
	(gen_random_uuid(), 'Neurocirurgião'),
	(gen_random_uuid(), 'Neurologista'),
	(gen_random_uuid(), 'Numerólogo'),
	(gen_random_uuid(), 'Nutricionista'),
	(gen_random_uuid(), 'Obstetra'),
	(gen_random_uuid(), 'Oceanógrafo'),
	(gen_random_uuid(), 'Oculista'),
	(gen_random_uuid(), 'Odontologista estético'),
	(gen_random_uuid(), 'Odontologista legal'),
	(gen_random_uuid(), 'Odontologista preventivo e social'),
	(gen_random_uuid(), 'Odontopediatra'),
	(gen_random_uuid(), 'Office-boy'),
	(gen_random_uuid(), 'Oficial de justiça'),
	(gen_random_uuid(), 'Oftalmologista'),
	(gen_random_uuid(), 'Ombudsman'),
	(gen_random_uuid(), 'Operador de telemarketing'),
	(gen_random_uuid(), 'Operador de vídeo'),
	(gen_random_uuid(), 'Optometrista'),
	(gen_random_uuid(), 'Orçamentista'),
	(gen_random_uuid(), 'Orientador Educacional'),
	(gen_random_uuid(), 'Ortesista'),
	(gen_random_uuid(), 'Ortodontista'),
	(gen_random_uuid(), 'Ortopedista'),
	(gen_random_uuid(), 'Ortoptista'),
	(gen_random_uuid(), 'Otorrinolaringologista'),
	(gen_random_uuid(), 'Ourives'),
	(gen_random_uuid(), 'Padeiro'),
	(gen_random_uuid(), 'Paginador'),
	(gen_random_uuid(), 'Paisagista'),
	(gen_random_uuid(), 'Panfleteiro'),
	(gen_random_uuid(), 'Paparazzo'),
	(gen_random_uuid(), 'Papiloscopista'),
	(gen_random_uuid(), 'Paraquedista'),
	(gen_random_uuid(), 'Parteira Tradicional'),
	(gen_random_uuid(), 'Passador'),
	(gen_random_uuid(), 'Pastilheiro'),
	(gen_random_uuid(), 'Patinador'),
	(gen_random_uuid(), 'Patologista'),
	(gen_random_uuid(), 'Patologista oral'),
	(gen_random_uuid(), 'Peão de rodeiro'),
	(gen_random_uuid(), 'Pecuarista'),
	(gen_random_uuid(), 'Pedagogo'),
	(gen_random_uuid(), 'Pediatra'),
	(gen_random_uuid(), 'Pedicure'),
	(gen_random_uuid(), 'Pedreiro'),
	(gen_random_uuid(), 'Peixeiro'),
	(gen_random_uuid(), 'Penhorista'),
	(gen_random_uuid(), 'Percursionista'),
	(gen_random_uuid(), 'Perfumista'),
	(gen_random_uuid(), 'Perfusionista'),
	(gen_random_uuid(), 'Perito Judicial'),
	(gen_random_uuid(), 'Personal stylist'),
	(gen_random_uuid(), 'Personal trainer'),
	(gen_random_uuid(), 'Pescador'),
	(gen_random_uuid(), 'Pesquisador'),
	(gen_random_uuid(), 'Petroleiro'),
	(gen_random_uuid(), 'Pianista'),
	(gen_random_uuid(), 'Piloto automobilístico'),
	(gen_random_uuid(), 'Piloto de avião'),
	(gen_random_uuid(), 'Pintor'),
	(gen_random_uuid(), 'Pizzaiolo'),
	(gen_random_uuid(), 'Plastimodelista'),
	(gen_random_uuid(), 'Pneumologista'),
	(gen_random_uuid(), 'Podólogo'),
	(gen_random_uuid(), 'Policial'),
	(gen_random_uuid(), 'Polidor de produção'),
	(gen_random_uuid(), 'Político'),
	(gen_random_uuid(), 'Porteiro'),
	(gen_random_uuid(), 'Portuário'),
	(gen_random_uuid(), 'Prático'),
	(gen_random_uuid(), 'Prefeito'),
	(gen_random_uuid(), 'Prensista'),
	(gen_random_uuid(), 'Preparador de máquinas'),
	(gen_random_uuid(), 'Presidente da Republica'),
	(gen_random_uuid(), 'Procurador de justiça'),
	(gen_random_uuid(), 'Produtor de eventos'),
	(gen_random_uuid(), 'Produtor editorial'),
	(gen_random_uuid(), 'Professor'),
	(gen_random_uuid(), 'Profissional de cinema'),
	(gen_random_uuid(), 'Profissional de comércio exterior'),
	(gen_random_uuid(), 'Profissional de educação física'),
	(gen_random_uuid(), 'Profissional de efeitos especiais'),
	(gen_random_uuid(), 'Profissional de hotelaria'),
	(gen_random_uuid(), 'Profissional de Informática'),
	(gen_random_uuid(), 'Profissional de logística'),
	(gen_random_uuid(), 'Profissional de marketing'),
	(gen_random_uuid(), 'Profissional de moda'),
	(gen_random_uuid(), 'Profissional de rádio e TV'),
	(gen_random_uuid(), 'Profissional de reciclagem'),
	(gen_random_uuid(), 'Profissional de relações internacionais'),
	(gen_random_uuid(), 'Profissional de relações públicas'),
	(gen_random_uuid(), 'Programador de sistemas de computação'),
	(gen_random_uuid(), 'Projetista mecánico'),
	(gen_random_uuid(), 'Promotor de eventos'),
	(gen_random_uuid(), 'Promotor de vendas'),
	(gen_random_uuid(), 'Promotor público'),
	(gen_random_uuid(), 'Protesista'),
	(gen_random_uuid(), 'Protético Dentário'),
	(gen_random_uuid(), 'Psicólogo'),
	(gen_random_uuid(), 'Psicomotricista'),
	(gen_random_uuid(), 'Psicopedagogo'),
	(gen_random_uuid(), 'Psiquiatra'),
	(gen_random_uuid(), 'Publicitário'),
	(gen_random_uuid(), 'Quadrinista'),
	(gen_random_uuid(), 'Químico'),
	(gen_random_uuid(), 'Químico farmacêutico'),
	(gen_random_uuid(), 'Quitandeiro'),
	(gen_random_uuid(), 'Radialista'),
	(gen_random_uuid(), 'Radiologista'),
	(gen_random_uuid(), 'Radio-operador de Vão'),
	(gen_random_uuid(), 'Radioterapêutico'),
	(gen_random_uuid(), 'Rebarbador de metal'),
	(gen_random_uuid(), 'Recepcionista'),
	(gen_random_uuid(), 'Recreador'),
	(gen_random_uuid(), 'Redator'),
	(gen_random_uuid(), 'Regente'),
	(gen_random_uuid(), 'Relações públicas'),
	(gen_random_uuid(), 'Remador'),
	(gen_random_uuid(), 'Repórter'),
	(gen_random_uuid(), 'Repositor'),
	(gen_random_uuid(), 'Representante comercial'),
	(gen_random_uuid(), 'Restaurador'),
	(gen_random_uuid(), 'Retificador'),
	(gen_random_uuid(), 'Reumatologista'),
	(gen_random_uuid(), 'Revendedor'),
	(gen_random_uuid(), 'Roteirista'),
	(gen_random_uuid(), 'Sacoleira'),
	(gen_random_uuid(), 'Salgadeira'),
	(gen_random_uuid(), 'Salva-vidas'),
	(gen_random_uuid(), 'Sapateiro'),
	(gen_random_uuid(), 'Sargento'),
	(gen_random_uuid(), 'Saxofonista'),
	(gen_random_uuid(), 'Secretária'),
	(gen_random_uuid(), 'Seguidor de compras'),
	(gen_random_uuid(), 'Segurança particular'),
	(gen_random_uuid(), 'Selecionador de pessoal'),
	(gen_random_uuid(), 'Senador'),
	(gen_random_uuid(), 'Separador'),
	(gen_random_uuid(), 'Seringueiro'),
	(gen_random_uuid(), 'Serralheiro'),
	(gen_random_uuid(), 'Servente-de-obras'),
	(gen_random_uuid(), 'Sexologista'),
	(gen_random_uuid(), 'Sexólogo'),
	(gen_random_uuid(), 'Síndico'),
	(gen_random_uuid(), 'Skatista'),
	(gen_random_uuid(), 'Sociólogo'),
	(gen_random_uuid(), 'Soldado'),
	(gen_random_uuid(), 'Soldador'),
	(gen_random_uuid(), 'Somelier'),
	(gen_random_uuid(), 'Sonoplasta'),
	(gen_random_uuid(), 'Subprefeito'),
	(gen_random_uuid(), 'Supervisor'),
	(gen_random_uuid(), 'Surfista'),
	(gen_random_uuid(), 'Sushiman'),
	(gen_random_uuid(), 'Taifeiro'),
	(gen_random_uuid(), 'Tapeceiro'),
	(gen_random_uuid(), 'Tatuador'),
	(gen_random_uuid(), 'Taxidermista'),
	(gen_random_uuid(), 'Taxidermista'),
	(gen_random_uuid(), 'Taxista'),
	(gen_random_uuid(), 'Tecelão'),
	(gen_random_uuid(), 'Técnico de som'),
	(gen_random_uuid(), 'Técnico em arquivo'),
	(gen_random_uuid(), 'Técnico em hardware'),
	(gen_random_uuid(), 'Técnico em Ã“ptica'),
	(gen_random_uuid(), 'Técnico em radiologia'),
	(gen_random_uuid(), 'Técnico em rede'),
	(gen_random_uuid(), 'Técnico em segurança do trabalho'),
	(gen_random_uuid(), 'Telefonista'),
	(gen_random_uuid(), 'Telegrafista'),
	(gen_random_uuid(), 'Tenente'),
	(gen_random_uuid(), 'Tenista'),
	(gen_random_uuid(), 'Teólogo'),
	(gen_random_uuid(), 'Terapeuta floral'),
	(gen_random_uuid(), 'Terapeuta ocupacional'),
	(gen_random_uuid(), 'Tesoureiro'),
	(gen_random_uuid(), 'Timoneiro'),
	(gen_random_uuid(), 'Tintureiro'),
	(gen_random_uuid(), 'Topógrafo'),
	(gen_random_uuid(), 'Torneiro mecánico'),
	(gen_random_uuid(), 'Toxicologista'),
	(gen_random_uuid(), 'Tradutor - Intérprete'),
	(gen_random_uuid(), 'Transcritor'),
	(gen_random_uuid(), 'Transportador'),
	(gen_random_uuid(), 'Traumatologista'),
	(gen_random_uuid(), 'Treinador'),
	(gen_random_uuid(), 'Triatleta'),
	(gen_random_uuid(), 'Trilheiro ou músico de cinema'),
	(gen_random_uuid(), 'Trompetista'),
	(gen_random_uuid(), 'Turismólogo'),
	(gen_random_uuid(), 'Ufólogo'),
	(gen_random_uuid(), 'Urbanista'),
	(gen_random_uuid(), 'Urologista'),
	(gen_random_uuid(), 'Velejador'),
	(gen_random_uuid(), 'Vendedor'),
	(gen_random_uuid(), 'Ventríloquo'),
	(gen_random_uuid(), 'Vereador'),
	(gen_random_uuid(), 'Veterinário'),
	(gen_random_uuid(), 'Vigilante noturno/diurno'),
	(gen_random_uuid(), 'Violonista'),
	(gen_random_uuid(), 'Vistoriador de sinistros'),
	(gen_random_uuid(), 'Viveirista'),
	(gen_random_uuid(), 'Web designer'),
	(gen_random_uuid(), 'Web master'),
	(gen_random_uuid(), 'Windsurfer'),
	(gen_random_uuid(), 'Xilógrafo'),
	(gen_random_uuid(), 'Zelador'),
	(gen_random_uuid(), 'Zootecnista'),
	(gen_random_uuid(), 'Outros');

INSERT INTO gisauserapidb.USUARIO     (id_usuario,    created_at, update_at, deteled, nome,                      email,                             cnpj,             cpf,           numero_sus,        sexo, cep,         endereco,                                     numero, bairro,   cidade,             uf,   estado_civil, data_cadastro, data_nascimento,              codigo_plano, valor_plano_mensal, id_profissao,      nivel_formacao, password)
VALUES
('83987b2a-db1d-474d-94eb-b818052dce56',              now(),      now(),     false,   'Maria Aparecida',         'maria.madalena@gmail.com',        '',               '65918656081', '898000195809566', 'M',  '71699-777', 'Quadra X Conjunto Y Casa Z - Brasilia - DF', 'Z',    'Centro', 'Distrito Federal', 'DF', 'Casado',     now(),         '2010-01-27 00:00:00.992673', '0001',       '600,00',           null, null,              '123'),
('daa53634-f45f-4c5c-9321-3376319dfe0c',              now(),      now(),     false,   'João Cleber',             'joao.bosco@gmail.com',            '',               '02638367036', '898000195809566', 'M',  '71699-777', 'Quadra X Conjunto Y Casa Z - Brasilia - DF', 'Z',    'Centro', 'Distrito Federal', 'DF', 'Casado',     now(),         '2005-07-20 00:00:00.992673', '0002',       '600,00',           null, null,              '123'),
('5cb24cc4-7099-4528-9cd0-eb18164db81b',              now(),      now(),     false,   'Sarah Kubscheck',         'gloria.menezes@gmail.com',        '',               '47997144064', '898000195809566', 'M',  '71699-777', 'Quadra X Conjunto Y Casa Z - Brasilia - DF', 'Z',    'Centro', 'Distrito Federal', 'DF', 'Casado',     now(),         '2003-08-17 00:00:00.992673', '0003',       '600,00',           null, null,              '123'),
('7709fae6-81d2-45ca-81d6-525a00d0b55d',              now(),      now(),     false,   'Juscelino Kubscheck',     'tarsizio.meira@gmail.com',        '',               '10165088087', '898000195809566', 'M',  '71699-777', 'Quadra X Conjunto Y Casa Z - Brasilia - DF', 'Z',    'Centro', 'Distrito Federal', 'DF', 'Casado',     now(),         '2000-03-11 00:00:00.992673', '0004',       '600,00',           null, null,              '123'),
('f2d89aa6-6318-419a-b8f9-5687f78702f0',              now(),      now(),     false,   'Hospital Sarah',          'hospitalsantalucia@gmail.com',    '50551582000172', '',            ''               , 'M',  '71699-777', 'Quadra X Conjunto Y Casa Z - Brasilia - DF', 'Z',    'Centro', 'Distrito Federal', 'DF', 'Casado',     now(),         '1996-05-08 00:00:00.992673', '',           '',                 null, null,              '123'),
('c82f8d64-9c99-4619-bed7-48148dbf69f2',              now(),      now(),     false,   'Hospital Anchieta',       'hospitalsantaluzia@gmail.com',    '95552223000178', '',            ''               , 'M',  '71699-777', 'Quadra X Conjunto Y Casa Z - Brasilia - DF', 'Z',    'Centro', 'Distrito Federal', 'DF', 'Casado',     now(),         '1987-11-27 00:00:00.992673', '',           '',                 null, null,              '123'),
('3489c2f1-8b64-4f30-882c-b4f52368bdb9',              now(),      now(),     false,   'Hospital Daher',          'dfstar@rededor.com',              '67604720000137', '',            ''               , 'M',  '71699-777', 'Quadra X Conjunto Y Casa Z - Brasilia - DF', 'Z',    'Centro', 'Distrito Federal', 'DF', 'Casado',     now(),         '1977-12-03 00:00:00.992673', '',           '',                 null, null,              '123'),
('39ee79d2-b82c-11eb-90fc-d706f35d9047',              now(),      now(),     false,   'Hospital Brasília',       'hospitalsiriolibanes@hsl.com',    '70327243000114', '',            ''               , 'M',  '71699-777', 'Quadra X Conjunto Y Casa Z - Brasilia - DF', 'Z',    'Centro', 'Distrito Federal', 'DF', 'Casado',     now(),         '1965-05-08 00:00:00.992673', '',           '',                 null, null,              '123'),
('1ca0164d-bb3a-4b85-840a-543d69dab7a8',              now(),      now(),     false,   'Hospital Santa Marta',    'hospitalsiriolibanes@gmail.com',  '04953315000104', '',            ''               , 'M',  '71699-777', 'Quadra X Conjunto Y Casa Z - Brasilia - DF', 'Z',    'Centro', 'Distrito Federal', 'DF', 'Casado',     now(),         '1988-10-07 00:00:00.992673', '',           '',                 null, null,              '123');
                                                                                                                                                                                                                                                      